--IN THE INVENTORY STRUCTURE DISPLAY :
--INVENTORY PROJECT
CREATE DATABASE INVENTORY;
USE INVENTORY;
--SUPPLIER TABLE
CREATE TABLE SUPPLIER
(SID CHAR(5) NOT NULL,
SNAME VARCHAR(20) NOT NULL,
SADD VARCHAR(20) NOT NULL,
SCITY VARCHAR(20) DEFAULT 'DELHI', 
SPHONE CHAR(15) UNIQUE,
SEMAIL VARCHAR(30));
SELECT * FROM SUPPLIER;
--PRODUCT TABLE
CREATE TABLE PRODUCT
(PID CHAR(5) NOT NULL,
PDESC VARCHAR(30) NOT NULL,
PRICE BIGINT CHECK(PRICE>0),
CATEGORY VARCHAR(30) CHECK(CATEGORY IN('IT','HOME APPLIANCE','HEALTH CARE')),
SID CHAR(5)); 
SELECT * FROM PRODUCT;
--STOCK TABLE
CREATE TABLE STOCK
(PID CHAR(5),
SQTY INT CHECK(SQTY>=0),
ROL INT CHECK(ROL>=0),
MOQ INT CHECK(MOQ>=5));
SELECT * FROM STOCK; 
--CUSTOMER TABLE
CREATE TABLE CUST
(CID CHAR(5) NOT NULL,
CNAME VARCHAR(20) NOT NULL,
CADDR VARCHAR(20) NOT NULL,
CCITY VARCHAR(20) NOT NULL,
CPHONE CHAR(15) NOT NULL,
CEMAIL VARCHAR(20) NOT NULL,
CDOB DATE CHECK(CDOB<'01-01-2000'));
SELECT * FROM CUST;
--ORDER TABLE
CREATE TABLE ORDERR
(OID CHAR(5) NOT NULL,
ODATE DATE,
PID CHAR(5),
CID CHAR(5),
OQTY BIGINT CHECK(OQTY>=1));
SELECT * FROM ORDERR;
--APPLYING PRIMARY KEY AND FOREGIN KEY TO THE TABLE
ALTER TABLE SUPPLIER ADD CONSTRAINT PK_S1 PRIMARY KEY(SID);
ALTER TABLE PRODUCT ADD CONSTRAINT PK_P1 PRIMARY KEY(PID);
ALTER TABLE PRODUCT ADD CONSTRAINT FK_P2 FOREIGN KEY(SID) REFERENCES SUPPLIER(SID);
ALTER TABLE CUST ADD CONSTRAINT C1 PRIMARY KEY(CID);
ALTER TABLE ORDERR ADD CONSTRAINT PK_O1 PRIMARY KEY(OID);
ALTER TABLE ORDERR ADD CONSTRAINT FK_O2 FOREIGN KEY(CID) REFERENCES CUST(CID);
ALTER TABLE ORDERR ADD CONSTRAINT FK_O3 FOREIGN KEY(PID) REFERENCES PRODUCT(PID);
ALTER TABLE STOCK ADD CONSTRAINT FK_S1 FOREIGN KEY(PID) REFERENCES PRODUCT(PID);
--INSERTING VALUES INTO THE TABLES
--SUPPLIER]
SELECT * FROM SUPPLIER;
INSERT INTO SUPPLIER VALUES
('S0001','APPLE','JANAKPURI WEST-','DELHI','9875673456','APPLESUPPORT@GMAIL.COM'),
('S0002','AK RETAILERS','KAROL BAGH-','DELHI','7845609020','AKRETAIL@GMAIL.COM'),
('S0003','SHOPMED','ANDHERI WEST-','MUMBAI','9006784589','MEDMIX589@GMAIL.COM'),
('S0004','INFINITE RETAIL','DLF PHASE-2','GURGAON','8934780656','CROMAINFINITERETAIL@GMAIL.COM'),
('S0005','HOME CARE','SHIVAJI NAGAR','KARNATAKA','9998500788','HOMECARE@GMAIL.COM');
--PRODUCT
SELECT * FROM PRODUCT;
INSERT INTO PRODUCT VALUES
('P0001','MACBOOK AIR',99900,'IT','S0001'),
('P0002','CHOPPER',2000,'HOME APPLIANCE','S0005'),
('P0003','BANDAGES',3000,'HEALTH CARE','S0003'),
('P0004','MARSHALL SPEAKER',25000,'IT','S0004'),
('P0005','STETHOSCOPE',10000,'HEALTH CARE','S0003'),
('P0006','OVEN',30000,'HOME APPLIANCE','S0005'),
('P0007','CHARGER',1900,'IT','S0001'),
('P0008','DINNING TABLE',40000,'HOME APPLIANCE','S0005'),
('P0009','SYRINGES',10000,'HEALTH CARE','S0003'),
('P0010','COMPUTER',75000,'IT','S0004'),
('P0011','STRING LIGHTS',5000,'HOME APPLIANCE','S0005'),
('P0012','TOASTER',15000,'HOME APPLIANCE','S0002'),
('P0013','NEEDLES',4000,'HEALTH CARE','S0003'),
('P0014','AIRPODS',25000,'IT','S0001'),
('P0015','PATIENT MONITER',25000,'HEALTH CARE','S0003'); 
--STOCK 
SELECT * FROM STOCK;
INSERT INTO STOCK VALUES
('P0001',8,4,10),
('P0010',6,3,8),
('P0012',3,4,10),
('P0003',10,10,30),
('P0006',5,8,10),
('P0009',15,2,15),
('P0015',30,1,18),
('P0008',1,2,9),
('P0011',20,4,10),
('P0014',10,2,40);
--CUST
SELECT * FROM CUST;
INSERT INTO CUST VALUES
('C0001','AKSHAY KUMAR','CHIRAG DILLI-SAKET','DELHI','9800745687','AKSHAY980@GMAIL.COM',
'1997-03-10'),
('C0002','SHREYA KAPOOR','DWARKA SEC 13','DELHI','8569764007','SHREYAK@GMAIL.COM',
'1994-01-07'),
('C0003','MALLARIE JAIN','TRANSCONTRIUMPH ROAD','MUMBAI','7009564367','MALLARIEJ@GMAIL.COM',
'1999-12-9'),
('C0004','ROHAN SHAH','CHANDER VILLAGE KAZI','KOLKATA','8368954349','ROAHANSHAH@GMAIL.COM',
'1995-08-30'),
('C0005','RIYA KOHLI','DLF PHASE 5','GURGAON','7908965800','RIYAKOHLI0@GMAIL.COM',
'1997-11-14');
--ORDER 
SELECT * FROM ORDERR;
INSERT INTO ORDERR VALUES
('O0001','2024-01-2','P0001','C0005',2),
('O0002','2023-4-30','P0004','C0001',3),
('O0003','2023-12-18','P0011','C0003',10),
('O0004','2024-2-7','P0013','C0002',30),
('O0005','2022-10-29','P0008','C0004',1);
--JOIN
--PID, PDESC, CATEGORY, SNAME, SCITY
SELECT PRODUCT.PID,PDESC,CATEGORY,SUPPLIER.SNAME,SCITY 
FROM PRODUCT 
INNER JOIN SUPPLIER
ON PRODUCT.SID=SUPPLIER.SID;
SELECT * FROM ORDERR;
SELECT * FROM SUPPLIER;
SELECT * FROM PRODUCT;
--DISPLAY OID , ODATE , CNAME, CADDRESS, CPHONE, PDESC, PRICE,OQTY, AMT
SELECT ORDERR.OID,ORDERR.ODATE,CUST.CNAME,CUST.CPHONE,PRODUCT.PDESC,PRODUCT.PRICE,
ORDERR.OQTY,
(PRODUCT.PRICE*ORDERR.OQTY) AS AMT
FROM ORDERR 
INNER JOIN CUST
ON ORDERR.CID=CUST.CID
INNER JOIN
PRODUCT
ON PRODUCT.PID=ORDERR.PID;
--CREATE BELOW PROCEDURES IN THE INVENTORY DATABASE AS SPECIFIED :
--ADD SUPPLIER:DISPLAY THE DETAILS OF THE NEW SUPPLIER ADDED 
CREATE PROCEDURE ADDSUPPLIER
@SID AS CHAR(5),
@SNAME AS VARCHAR(20),
@SADD AS VARCHAR(30),
@SCITY AS VARCHAR(20),
@SPHONE AS VARCHAR(15),
@SEMAIL AS VARCHAR(40)
AS
BEGIN
INSERT INTO SUPPLIER VALUES(@SID,@SNAME,@SADD,@SCITY,@SPHONE,@SEMAIL)
SELECT * FROM SUPPLIER WHERE SID=@SID
END
EXECUTE ADDSUPPLIER 'S0006','INNOVATEK SOLUTIONS','PLOT 22-SECTOR 26','NOIDA','9868798986','INNOVATEKPVT@GMAIL.COM'
SELECT * FROM SUPPLIER;
--ADDPRO:DISPLAY THE DETAILS OF THE NEW PRODUCT ADDED
SELECT * FROM PRODUCT;
CREATE PROCEDURE ADDPRO
@PID AS CHAR(5),
@PDESC AS VARCHAR(20),
@PRICE AS INT,
@CATEGORY AS VARCHAR(20),
@SID AS CHAR(5)
AS
BEGIN
INSERT INTO PRODUCT VALUES(@PID,@PDESC,@PRICE,@CATEGORY,@SID)
SELECT * FROM PRODUCT WHERE PID=@PID
END
EXECUTE ADDPRO 'P0016','PRINTER',11000,'IT','S0006'
--ADDCUST:DISPLAY THE DETAILS OF THE NEW CUSTOMER ADDED
SELECT * FROM CUST;
CREATE PROCEDURE ADDCUST
@CID AS CHAR(5),
@CNAME AS VARCHAR(20),
@CADDR AS VARCHAR(20),
@CCITY AS VARCHAR(20),
@CPHONE AS VARCHAR(15),
@CEMAIL AS VARCHAR(30),
@CDOB AS DATE
AS
BEGIN
INSERT INTO CUST VALUES(@CID,@CNAME,@CADDR,@CCITY,@CPHONE,@CEMAIL,@CDOB)
SELECT * FROM CUST WHERE CID=@CID
END
EXECUTE ADDCUST 'C0006','NAVYA CHAUDHARY','SHASTRI NAGAR-MEERUT-250004,','UTTAR PRADESH','8967545656',
'NAVYA02@GMAIL.COM','1999-11-02'
--ADDORDER:DISPLAY THE DETAILS OF THE ORDER.ORDER DATE SHOULD BE CURRENT DATE AND SHOULD COME AUTOMATICALLY.
SELECT * FROM ORDERR;
CREATE PROCEDURE ADDORDER
@OID AS CHAR(5),
@PID AS CHAR(5),
@CID AS CHAR(5),
@OQTY AS INT
AS
BEGIN
INSERT INTO ORDERR VALUES(@OID,GETDATE(),@PID,@CID,@OQTY)
SELECT * FROM ORDERR WHERE OID=@OID
END
EXECUTE ADDORDER 'O0006','P0016','C0006',2
--ALL THE IDS SHOULD BE AUTOMATICALLY GENERATED USING ABOVE CREATED FUNCTION AND SEQUENCES USING STORED PROCEDURE
--ADDSUPPLIER:DISPLAY THE DETAILS OF THE NEW SUPPLIER ADDED
SELECT * FROM SUPPLIER;
CREATE FUNCTION IDGENERATE(@C AS CHAR(1),@NUM AS INT)
RETURNS VARCHAR(10)
AS
BEGIN
DECLARE @ID AS VARCHAR(10)
IF LEN(@NUM)=1
BEGIN 
SET @ID=CONCAT(@C,'000',@NUM)
END 
ELSE IF LEN(@NUM)=2
BEGIN 
SET @ID=CONCAT(@C,'00',@NUM)
END 
ELSE IF LEN(@NUM)=3
BEGIN 
SET @ID=CONCAT(@C,'0',@NUM)
END
ELSE IF LEN(@NUM)=4
BEGIN 
SET @ID=CONCAT(@C,@NUM)
END 
RETURN @ID
END;
CREATE PROCEDURE ADD_SUPPLIER
@SNAME AS VARCHAR(20),
@SADD AS VARCHAR(20),
@SCITY AS VARCHAR(20),
@SPHONE AS VARCHAR(15),
@SEMAIL AS VARCHAR(30)
AS 
BEGIN 
DECLARE @TOTALROW AS INT,@SID AS CHAR(5);
SELECT @TOTALROW=COUNT(*)+1 FROM SUPPLIER
SELECT @SID=DBO.IDGENERATE('S',@TOTALROW)
INSERT INTO SUPPLIER VALUES(@SID,@SNAME,@SADD,@SCITY,@SPHONE,@SEMAIL);
SELECT * FROM SUPPLIER WHERE SID=@SID
END;
EXECUTE ADD_SUPPLIER 'BRIGHT HOME PVT LTD','NUNGAMBAKKAN HIGH ROAD','CHENNAI','8779965477',
'BRIGHTHOME@SUPPORT.IN'
--ADDPRO:DISPLAY THE DETAILS OF THE NEW PRODUCT ADDED
SELECT * FROM PRODUCT;
CREATE PROCEDURE ADD_PRO
@PDESC AS VARCHAR(20),
@PRICE AS INT,
@CATEGORY AS VARCHAR(20),
@SID AS CHAR(5)
AS 
BEGIN 
DECLARE @TOTALROW AS INT,@PID AS CHAR(5);
SELECT @TOTALROW=COUNT(*)+1 FROM PRODUCT
SELECT @PID=DBO.IDGENERATE('P',@TOTALROW)
INSERT INTO PRODUCT VALUES(@PID,@PDESC,@PRICE,@CATEGORY,@SID);
SELECT * FROM PRODUCT WHERE PID=@PID
END;
EXECUTE ADD_PRO 'LAMP',10000,'HOME APPLIANCE','S0007'
--ADDCUST:DISPLAY THE DETAILS OF THE NEW PRODUCT ADDED
SELECT * FROM CUST;
CREATE PROCEDURE ADD_CUST
@CNAME AS VARCHAR(20),
@CADDR AS VARCHAR(30),
@CCITY AS VARCHAR(20),
@CPHONE AS VARCHAR(15),
@CEMAIL AS VARCHAR(30),
@CDOB AS DATE
AS 
BEGIN 
DECLARE @TOTALROW AS INT,@CID AS CHAR(5);
SELECT @TOTALROW=COUNT(*)+1 FROM CUST
SELECT @CID=DBO.IDGENERATE('C',@TOTALROW)
INSERT INTO CUST VALUES(@CID,@CNAME,@CADDR,@CCITY,@CPHONE,@CEMAIL,@CDOB);
SELECT * FROM CUST WHERE CID=@CID
END;
EXECUTE ADD_CUST 'KARTIK DIXIT','N BLOCK GK-I','DELHI','8889967954','KARTIKD09@GMAIL.COM','1998-6-12'
--ADDORDER:DISPLAY THE DETAILS OF THE NEW PRODUCT ADDED
SELECT * FROM ORDERR;
CREATE PROCEDURE ADD_ORDERR
@PID AS CHAR(5),
@CID AS CHAR(5),
@OQTY AS INT
AS 
BEGIN 
DECLARE @TOTALROW AS INT,@OID AS CHAR(5);
SELECT @TOTALROW=COUNT(*)+1 FROM ORDERR
SELECT @OID=DBO.IDGENERATE('O',@TOTALROW)
INSERT INTO ORDERR VALUES(@OID,GETDATE(),@PID,@CID,@OQTY);
SELECT * FROM ORDERR WHERE OID=@OID
END;
DROP PROCEDURE ADD_ORDERR;
EXECUTE ADD_ORDERR 'P0017','C0007',5
/* IN THE INVENTORY STRUCTURE GENERATE A VIEW AS BILL. IT SHOULD DISPLAY OID,ODATE,CNAME,ADDRESS,PHONE,
PDESC,PRICE,OQTY,AMOUNT*/
CREATE VIEW BILL AS 
SELECT ORDERR.OID,ORDERR.ODATE,CUST.CNAME,CUST.CADDR,CUST.CPHONE,PRODUCT.PDESC,PRODUCT.PRICE,ORDERR.OQTY,
(PRODUCT.PRICE * ORDERR.OQTY) AS AMOUNT
FROM ORDERR
INNER JOIN CUST
ON ORDERR.CID=CUST.CID
INNER JOIN
PRODUCT
ON PRODUCT.PID=ORDERR.PID;
SELECT * FROM BILL;